apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: mce-sample-pipelinerun
  namespace: multicluster-engine
spec:
  pipelineRef:
    name: deploy-sample-apps
  params:
    - name: aws-secret
      value: aws-creds
    - name: ocp-pull-secret
      value: ocp-pull-secret
    - name: namespace
      value: multicluster-engine
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: multiclusterengine-samples