apiVersion: hive.openshift.io/v1
kind: ClusterPool
metadata:
  name: aws-pool
spec:
  baseDomain: dev01.red-chesterfield.com
  imageSetRef:
    name: img4.9.4-x86-64-appsub
  installConfigSecretTemplateRef:
    name: installer-config-template
  platform:
    aws:
      credentialsSecretRef:
        name: ""
      region: us-east-1
  pullSecretRef:
    name: ""
  size: 0