apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
  namespace: openshift-pipelines
spec:
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: https://github.com/zkayyali812/mce-samples.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: apply-clusterdeployment
    params:
    - name: manifest_dir
      value: resources/clusterdeployment
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace