apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multiclusterengine-samples
  namespace: multicluster-engine
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem