apiVersion: hive.openshift.io/v1
kind: SelectorSyncSet
metadata:
  name: sync-icsp
spec:
  resources:
  - apiVersion: operator.openshift.io/v1alpha1
    kind: ImageContentSourcePolicy
    metadata:
      name: rhacm-repo
    spec:
      repositoryDigestMirrors:
      - mirrors:
        - quay.io:443/acm-d
        source: registry.redhat.io/rhacm2
      - mirrors:
        - quay.io:443/acm-d
        source: registry.redhat.io/multicluster-engine
      - mirrors:
        - registry.redhat.io/openshift4/ose-oauth-proxy
        source: registry.access.redhat.com/openshift4/ose-oauth-proxy
  clusterDeploymentSelector:
    matchLabels:
      hive.openshift.io/cluster-platform: aws