apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-acm
  namespace: openshift-pipelines
spec:
  params:
  - name: clusterPoolName
    type: string
    description: The name of the clusterpool to use
    default: "policy-aas-hubs"
  - name: clusterPoolNamespace
    type: string
    description: The namespace to search for the clusterpool
    default: "managed-services"
  - name: clusterClaimName
    type: string
    description: The name of the clusterclaim to use
    default: "zkayyali-test"
  - name: namespace
    type: string
    description: The namespace to deploy ACM into
    default: "open-cluster-management"
  - name: imagePullSecret
    type: string
    description: The image pull secret used to deploy the catalogsources. Copied from clusterPoolNamespace
    default: "multiclusterhub-operator-pull-secret"
  - name: snapshotTag
    type: string
    description: The SNAPSHOT Tag used to deploy the catalogsources
    default: "SNAPSHOT"
  tasks:
  - name: fetch-repo-samples
    params:
    - name: url
      value: https://github.com/zkayyali812/mce-samples.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: fetch-repo-hypershift
    params:
    - name: url
      value: https://github.com/openshift/hypershift.git
    - name: revision
      value: main
    - name: deleteExisting
      value: "true"
    - name: subdirectory
      value: "hypershift"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: checkout-cluster
    params:
    - name: clusterClaimName
      value: $(params.clusterClaimName)
    - name: clusterPoolName
      value: $(params.clusterPoolName)
    - name: clusterPoolNamespace
      value: $(params.clusterPoolNamespace)
    - name: imagePullSecret
      value: $(params.imagePullSecret)
    runAfter:
    - fetch-repo-samples
    taskRef:
      kind: Task
      name: checkout-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: login-to-cluster
    params:
    - name: username
      value: "$(tasks.checkout-cluster.results.username)"
    - name: password
      value: "$(tasks.checkout-cluster.results.password)"
    - name: api
      value: "$(tasks.checkout-cluster.results.api)"
    runAfter:
    - checkout-cluster
    taskRef:
      kind: Task
      name: login-to-cluster
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-acm-prereqs
    params:
    - name: namespace
      value: "$(params.namespace)"
    - name: imagePullSecretName
      value: "$(params.imagePullSecret)"
    - name: imagePullSecret
      value: "$(tasks.checkout-cluster.results.imagePullSecret)"
    - name: snapshotTag
      value: "$(params.snapshotTag)"
    runAfter:
    - login-to-cluster
    taskRef:
      kind: Task
      name: apply-acm-prereqs
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-and-wait-for-subscription
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - apply-acm-prereqs
    taskRef:
      kind: Task
      name: apply-and-wait-for-subscription
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-and-wait-for-mch
    params:
    - name: namespace
      value: $(params.namespace)
    - name: imagePullSecret
      value: $(params.imagePullSecret)
    runAfter:
    - apply-and-wait-for-subscription
    taskRef:
      kind: Task
      name: apply-and-wait-for-mch
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: apply-and-wait-for-hypershift
    params:
    - name: namespace
      value: $(params.namespace)
    runAfter:
    - apply-acm-prereqs
    - fetch-repo-hypershift
    taskRef:
      kind: Task
      name: apply-and-wait-for-hypershift
    workspaces:
    - name: source
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace