apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acm-deploy-pipeline-pvc
  namespace: openshift-pipelines
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: gp2
  volumeMode: Filesystem