# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: spoke-cluster1
stringData:
  autoImportRetry: "5"
  kubeconfig: |- 
    ""
type: Opaque
