# Copyright Contributors to the Open Cluster Management project

apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
     environment: Dev
    cluster.open-cluster-management.io/clusterset: clusterset1
  name: spoke-cluster1
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
